# ~*~ coding: utf-8 ~*~

# miron-client version:
MIRON_VERSION = 

# load actions:
HELP_LOAD_ACTION = 100
VERSION_LOAD_ACTION = 90
CONFIG_LOAD_ACTION = 80
CREATE_INIT_LOAD_ACTION = 70
SET_LOAD_ACTION = 60
UPDATE_LOAD_ACTION = 50
HARDWARE_LOAD_ACTION = 40
READY_LOAD_ACTION = 30
MAIN_LOAD_ACTION = 10
