# ~*~ coding: utf-8 ~*~

# miron-client version:
MIRON_VERSION = "1.0.0"

# load actions:
HELP_LOAD_ACTION = 100
VERSION_LOAD_ACTION = 90
CONFIG_LOAD_ACTION = 80
CREATE_INIT_LOAD_ACTION = 70
SET_LOAD_ACTION = 60
HARDWARE_LOAD_ACTION = 50
READY_LOAD_ACTION = 40
MAIN_LOAD_ACTION = 20
