#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          miron-client
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop miron-client
# Description:       Start and stop miron-client.
### END INIT INFO
#
RUN=/usr/bin/miron-client
INFO=/etc/miron-client/info.xml

test -f $RUN || exit 0

case $1 in
	start)
		sudo lshw -xml > $INFO
		sudo $RUN
	;;
	stop)
		killall -SIGHUP $RUN
	;;
	reload | force-reload)
		killall -SIGHUP $RUN
		sudo lshw -xml > $INFO
		sudo $RUN
	;;
	restart)
		killall -SIGHUP $RUN
		sudo $RUN
	;;
esac
